runtime: python39
entrypoint: gunicorn -b :$PORT Tokoroten_ver0_web.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "Tokoroten_ver0_web.settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
